name: code_steps
description: Platform for rapidly developing step-by-step tutorials with robust features for content creators
version: 0.4.0
environment:
  sdk: any
dependencies:
  angular2: any
  browser: any
  dart_to_js_script_rewriter: any
  js: any
  ace: any
  ng_bootstrap: any
  jsonx: any
  fff: any
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
